# Generated by Django 2.2.10 on 2022-05-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_active',
        ),
    ]
