# Generated by Django 3.2 on 2022-05-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': '用户名只能是唯一的'}, help_text='请输入用户名', max_length=150, unique=True, verbose_name='用户名'),
        ),
    ]
