# Generated by Django 3.2 on 2022-05-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_userhome_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='home',
            name='mobile',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='home',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='收货人'),
        ),
    ]
