# Generated by Django 3.2 on 2022-05-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220521_1841'),
    ]

    operations = [
    ]
