# Generated by Django 3.2 on 2022-05-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_home_receiver'),
    ]

    operations = [
    ]
