# Generated by Django 3.2 on 2022-05-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_home_receive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='user',
        ),
    ]
