# Generated by Django 3.2 on 2022-05-21 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20220521_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='receive',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='收货人'),
        ),
        migrations.AddField(
            model_name='home',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
