# Generated by Django 3.2 on 2022-05-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20220521_1903'),
    ]

    operations = [

    ]
