# Generated by Django 3.2 on 2022-05-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='md_Category',
        ),
        migrations.AlterModelTable(
            name='computergoods',
            table='md_Computer_Goods',
        ),
        migrations.AlterModelTable(
            name='computerspecification',
            table='md_Computer_Specification',
        ),
        migrations.AlterModelTable(
            name='estimate',
            table='md_Estimate',
        ),
        migrations.AlterModelTable(
            name='mobilegoods',
            table='md_Mobile_Goods',
        ),
        migrations.AlterModelTable(
            name='mobilespecification',
            table='md_Mobile_Specification',
        ),
    ]
