# Generated by Django 3.2 on 2022-05-19 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20220519_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computergoods',
            options={'verbose_name': '电脑商品', 'verbose_name_plural': '电脑商品'},
        ),
        migrations.AlterField(
            model_name='mobilegoods',
            name='estimate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.estimate', verbose_name='商品评价'),
        ),
    ]
