# Generated by Django 3.2 on 2022-05-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_mobilegoods_estimate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computergoods',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='mobilegoods',
            name='estimate',
        ),
        migrations.AddField(
            model_name='estimate',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.computergoods', verbose_name='电脑'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.mobilegoods', verbose_name='手机'),
        ),
    ]
