# Generated by Django 3.2 on 2022-05-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_estimate_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computergoods',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='mobilegoods',
            name='specification',
        ),
        migrations.AddField(
            model_name='computerspecification',
            name='mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.mobilegoods', verbose_name='商品名称'),
        ),
        migrations.AddField(
            model_name='mobilespecification',
            name='mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.mobilegoods', verbose_name='商品名称'),
        ),
    ]
