# Generated by Django 3.2 on 2022-05-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20220519_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerspecification',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='mobilespecification',
            name='mobile',
        ),
        migrations.AddField(
            model_name='computergoods',
            name='specification_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_1', to='goods.computerspecification', verbose_name='商品规格1'),
        ),
        migrations.AddField(
            model_name='computergoods',
            name='specification_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_2', to='goods.computerspecification', verbose_name='商品规格2'),
        ),
        migrations.AddField(
            model_name='computergoods',
            name='specification_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_3', to='goods.computerspecification', verbose_name='商品规格3'),
        ),
        migrations.AddField(
            model_name='mobilegoods',
            name='specification_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_1', to='goods.mobilespecification', verbose_name='商品规格1'),
        ),
        migrations.AddField(
            model_name='mobilegoods',
            name='specification_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_2', to='goods.mobilespecification', verbose_name='商品规格2'),
        ),
        migrations.AddField(
            model_name='mobilegoods',
            name='specification_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_3', to='goods.mobilespecification', verbose_name='商品规格3'),
        ),
    ]
