# Generated by Django 3.2 on 2022-05-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20220519_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerspecification',
            name='size',
        ),
        migrations.AddField(
            model_name='computerspecification',
            name='size_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='尺寸1'),
        ),
        migrations.AddField(
            model_name='computerspecification',
            name='size_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='尺寸2'),
        ),
    ]
