# Generated by Django 3.2 on 2022-05-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20220519_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='computergoods',
            name='account',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='mobilegoods',
            name='account',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='商品描述'),
        ),
    ]
