# Generated by Django 3.2 on 2022-05-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20220519_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerspecification',
            name='size_1',
        ),
        migrations.RemoveField(
            model_name='computerspecification',
            name='size_2',
        ),
        migrations.AddField(
            model_name='computerspecification',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='尺寸'),
        ),
    ]
