# Generated by Django 3.2 on 2022-05-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20220520_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computergoods',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='商品名称'),
        ),
    ]
