# Generated by Django 3.2 on 2022-05-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_alter_computergoods_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computergoods',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='商品名称'),
        ),
    ]
