# Generated by Django 3.2 on 2022-06-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_alter_computergoods_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computergoods',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='mobilegoods',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='商品图片'),
        ),
    ]
