# Generated by Django 3.2 on 2022-05-24 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_home_user'),
        ('order', '0003_order_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.home', verbose_name='关联地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='支付方式'),
        ),
    ]
