# Generated by Django 3.2 on 2022-05-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderinfo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_count',
            field=models.FloatField(blank=True, null=True, verbose_name='订单总价'),
        ),
    ]
